export const posts = [
  { slug: "the-quiet-craft", title: "The quiet craft of making things simple", excerpt: "Simplicity isn’t where a project begins. It’s what remains after the hard decisions and careful edits.", category: "Engineering", date: "August 12, 2026", isoDate: "2026-08-12", readTime: "4 min", sections: [
    { title: "Simple is something you arrive at", paragraphs: ["A first draft of a system is usually a map of everything we don’t understand yet. There are extra switches, provisional names, and abstractions that promise to be useful later. That isn’t a failure. It is part of finding the shape of the problem.", "The mistake is treating that first shape as permanent. Simplicity arrives through a second pass: looking at what the system actually needs to do, and removing the parts that only describe what it might do someday."] },
    { title: "Make the ordinary path obvious", paragraphs: ["I try to start with a question: can someone follow the most common request without jumping between six files? A small amount of repetition can be a good trade if it makes the answer easier to find.", "Give the important operations plain names. Put related decisions close together. Keep the boundary between a request, a business rule, and a storage operation visible. These are small choices, but their effect accumulates."] },
    { title: "Leave room for the next person", paragraphs: ["A good explanation is a useful design test. If I need a long preamble to explain why a component exists, I may have hidden too much context inside it. Sometimes the fix is a comment. Sometimes it is deleting the component.", "The next person is often me, three months later. I want to leave that person a system with a few clear rules and an honest account of its trade-offs. That is the quiet work: editing until the essential decisions are easy to see."] },
  ] },
  { slug: "a-writing-habit", title: "Building a writing habit that survives busy weeks", excerpt: "A small system for capturing ideas and publishing without waiting for perfect conditions.", category: "Process", date: "August 7, 2026", isoDate: "2026-08-07", readTime: "3 min", sections: [
    { title: "Lower the cost of starting", paragraphs: ["An empty page asks for too many decisions at once. What is the subject? Who is it for? How long should it be? I find it easier to collect small observations while working, before they need to become an article.", "One surprising error message, one useful question, one explanation that finally made sense: each is enough for a note. Capture the detail while it is still specific."] },
    { title: "Separate collecting from editing", paragraphs: ["Collecting is generous. Editing is selective. Doing both at the same time makes every sentence feel like a commitment. A notebook gives unfinished thoughts a place to wait.", "When there is time to write, choose one note and explain what changed in your understanding. Start with the concrete problem. Show the useful detail. Stop when the explanation is complete."] },
    { title: "Let small pieces count", paragraphs: ["A habit that only works on a quiet weekend is a fragile habit. A short, accurate explanation can be more useful than an ambitious essay that never leaves the drafts folder.", "The goal is not to publish everything. It is to keep noticing, and to give the observations worth keeping a little more shape."] },
  ] },
  { slug: "why-ktor", title: "Why I reached for Ktor on my next side project", excerpt: "A small backend, a familiar language, and just enough structure to keep moving.", category: "Kotlin", date: "July 29, 2026", isoDate: "2026-07-29", readTime: "3 min", sections: [
    { title: "Start with the size of the problem", paragraphs: ["A personal blog needs a modest backend. It needs a few clear endpoints, predictable authentication, and a development loop that makes changes easy to inspect. I wanted the code to stay close to those requirements.", "Ktor fits the way I like to work in Kotlin: explicit routes, small modules, and room to choose the pieces a project actually needs."] },
    { title: "Keep the boundary understandable", paragraphs: ["In this project, the frontend owns the reading experience and the backend owns authentication. That boundary makes it easier to reason about both. The login form sends a request, the API validates it, and the frontend handles the result.", "The useful part is not the number of frameworks involved. It is being able to describe the contract between them without explaining the whole application."] },
    { title: "Choose trade-offs deliberately", paragraphs: ["A small framework still asks you to make decisions. Error responses, configuration, and deployment do not design themselves. That is a reasonable trade when the scope is clear and the choices are documented.", "I am choosing a tool for this project, not declaring a winner for every backend. Familiarity and a clear fit matter more than collecting features I do not need yet."] },
  ] },
  { slug: "boring-architecture", title: "The boring architecture is usually the good one", excerpt: "Clear boundaries, fewer abstractions, and systems you can still explain six months later.", category: "Engineering", date: "July 18, 2026", isoDate: "2026-07-18", readTime: "3 min", sections: [
    { title: "Optimize for understanding", paragraphs: ["The most useful architecture is often the one that makes an ordinary change unsurprising. You know where the request enters, where the decision happens, and where the data goes.", "A diagram with fewer boxes is not automatically simpler. The question is whether those boxes correspond to real responsibilities, and whether their connections are easy to follow."] },
    { title: "Wait for a real pattern", paragraphs: ["It is tempting to build a flexible layer before there is anything concrete to vary. But imagined requirements are poor evidence. A second real use case teaches more than a dozen hypothetical ones.", "Keep the first version direct. When repetition reveals a stable concept, extract that concept and give it a name that explains its purpose."] },
    { title: "Write down the reason", paragraphs: ["Code shows what a system does. A short note can explain why an otherwise reasonable alternative was not chosen. Record the constraint, the decision, and what would cause you to revisit it.", "Boring architecture is not a lack of care. It is care directed toward the people who will operate, change, and understand the system after the novelty wears off."] },
  ] },
];
