ktor:
  application:
    modules:
      - dev.jimmy.blog.ApplicationKt.module
  deployment:
    host: "0.0.0.0"
    port: "$PORT:8080"
jwt:
  issuer: "jimmy-blog-api"
  audience: "jimmy-blog-web"
  realm: "Jimmy's Notes"
